headers:
  all:
    request:
      - propagate:
          named: "Authorization"
cors:
  origins:
    - http://localhost:3000
include_subgraph_errors:
  all: true
rhai:
  scripts: "./scripts"
  main: "main.rhai"
sandbox:
  enabled: true
homepage:
  enabled: false
supergraph:
  introspection: true
